### ISSUE TITLE
evaluate.py for different random seeds

### ISSUE THREAD

**Issue by wyin1632** [yandex-research/tabm#9]
The doc suggests that `evaluate.py` can train the model under different random seeds for function `model.bin.main`. I want to use a custom config as follows.

```toml
seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00046156856557107476
weight_decay = 0.0

[model]
arch_type = "tabm"
k = 32

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 448
dropout = 0.03497913168507137
```

Is the random seed used to create different train-test split? It seems that the `build_dataset` always load the same data splits and the random seed is only used in `dataset['x_num'] = transform_num(dataset['x_num'], num_policy, seed)`.
